Weina Ke Capstone 2
11/20/2022

In [1]:
import pandas as pd

Data acquried from web scraping the journal information from https://exaly.com/

In [24]:
# Read csv into a pandas dataset
raw_df = pd.read_csv('Master_literature_impact_factor_file_11_15.csv')
raw_df.head()

,jornal_url,journal,article_number,citation_number,impact_factor,most_cited,year,cited_by
0,/journal/35949/cancer-nanotechnology,Cancer Nanotechnology,136.0,3100.0,7.3,Gold nanoparticles for cancer radiotherapy: a ...,2016.0,227.0
1,/journal/20204/nano,Nano,1600.0,8900.0,1.1,INVESTIGATION OF HOMOLOGOUS SERIES AS PRECURSO...,2011.0,217.0
2,/journal/12736/nanotechnology,Nanotechnology,20200.0,547400.0,3.3,The bactericidal effect of silver nanoparticles,2005.0,4600.0
3,/journal/27969/nano-structures-nano-objects,Nano Structures Nano Objects,576.0,7200.0,5.5,Recent developments in functionalized polymer ...,2019.0,137.0
4,/journal/88571/advances-in-nano-optics-and-nan...,Advances in Nano-optics and Nano-photonics,18.0,3.0,NaN,Chapter 3 Super-resolution microscopy using su...,2006.0,1.0

In [26]:
# Rename columns to facilitate understanding
raw_df_rn = raw_df.rename(index=str, columns={"citation_number":"Total_number_of_citation", "cited_by":"Citation_most_cited_article", "year":"Year_of_most_cited_article"})
raw_df_rn.head()

,jornal_url,journal,article_number,Total_number_of_citation,impact_factor,most_cited,Year_of_most_cited_article,Citation_most_cited_article
0,/journal/35949/cancer-nanotechnology,Cancer Nanotechnology,136.0,3100.0,7.3,Gold nanoparticles for cancer radiotherapy: a ...,2016.0,227.0
1,/journal/20204/nano,Nano,1600.0,8900.0,1.1,INVESTIGATION OF HOMOLOGOUS SERIES AS PRECURSO...,2011.0,217.0
2,/journal/12736/nanotechnology,Nanotechnology,20200.0,547400.0,3.3,The bactericidal effect of silver nanoparticles,2005.0,4600.0
3,/journal/27969/nano-structures-nano-objects,Nano Structures Nano Objects,576.0,7200.0,5.5,Recent developments in functionalized polymer ...,2019.0,137.0
4,/journal/88571/advances-in-nano-optics-and-nan...,Advances in Nano-optics and Nano-photonics,18.0,3.0,NaN,Chapter 3 Super-resolution microscopy using su...,2006.0,1.0

In [27]:
# Drop columns that are not interested in 
df_target = raw_df_rn.drop(['jornal_url', 'most_cited'], axis=1)
df_target.head()

,journal,article_number,Total_number_of_citation,impact_factor,Year_of_most_cited_article,Citation_most_cited_article
0,Cancer Nanotechnology,136.0,3100.0,7.3,2016.0,227.0
1,Nano,1600.0,8900.0,1.1,2011.0,217.0
2,Nanotechnology,20200.0,547400.0,3.3,2005.0,4600.0
3,Nano Structures Nano Objects,576.0,7200.0,5.5,2019.0,137.0
4,Advances in Nano-optics and Nano-photonics,18.0,3.0,NaN,2006.0,1.0

In [28]:
# Get general information on the dataframe of interest
df_target.info()

<class 'pandas.core.frame.DataFrame'>
Index: 479 entries, 0 to 478
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   journal                      479 non-null    object
 1   article_number               479 non-null    float64
 2   Total_number_of_citation     475 non-null    float64
 3   impact_factor                327 non-null    float64
 4   Year_of_most_cited_article   470 non-null    float64
 5   Citation_most_cited_article  474 non-null    float64
dtypes: float64(5), object(1)
memory usage: 26.2+ KB

In [29]:
# Drop rows with NA
df_target.dropna(inplace=True)
df_target.info()

<class 'pandas.core.frame.DataFrame'>
Index: 323 entries, 0 to 475
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   journal                      323 non-null    object
 1   article_number               323 non-null    float64
 2   Total_number_of_citation     323 non-null    float64
 3   impact_factor                323 non-null    float64
 4   Year_of_most_cited_article   323 non-null    float64
 5   Citation_most_cited_article  323 non-null    float64
dtypes: float64(5), object(1)
memory usage: 17.7+ KB

In [30]:
# Drop potential duplicated rows
df_target.drop_duplicates()
df_target.info()

<class 'pandas.core.frame.DataFrame'>
Index: 323 entries, 0 to 475
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   journal                      323 non-null    object
 1   article_number               323 non-null    float64
 2   Total_number_of_citation     323 non-null    float64
 3   impact_factor                323 non-null    float64
 4   Year_of_most_cited_article   323 non-null    float64
 5   Citation_most_cited_article  323 non-null    float64
dtypes: float64(5), object(1)
memory usage: 17.7+ KB

In [58]:
# Group mosted cited article (mca) by year to see the "popularity" of the journal
df_group_mca = df_target.set_index('Year_of_most_cited_article').groupby('Year_of_most_cited_article')
df_group_mca.head()

,journal,article_number,Total_number_of_citation,impact_factor,Citation_most_cited_article
Year_of_most_cited_article,,,,,
2016.0,Cancer Nanotechnology,136.0,3100.0,7.3,227.0
2011.0,Nano,1600.0,8900.0,1.1,217.0
2005.0,Nanotechnology,20200.0,547400.0,3.3,4600.0
2019.0,Nano Structures Nano Objects,576.0,7200.0,5.5,137.0
2008.0,Nano Letters,18100.0,1800000.0,11.3,9700.0
...,...,...,...,...,...
2006.0,Journal of the National Comprehensive Cancer N...,2900.0,63600.0,6.4,349.0
1968.0,Cancer Studies and Molecular Medicine: Open Jo...,39.0,54.0,0.6,140.0
1988.0,International Journal of Clinical Oncology and...,42.0,6.0,0.1,48.0
1977.0,American Journal of Clinical Oncology: Cancer ...,5400.0,98300.0,2.6,17.0
1987.0,Frontiers in Clinical Drug Research Anti-cance...,22.0,1.0,0.1,938.0

In [59]:
# See count of the year of most cited article
df_mca_count = df_group_mca.count()
df_mca_count = df_mca_count.sort_values(by=['journal'],ascending=False)
Count_info = df_mca_count.journal
print(Count_info.head(15))

Year_of_most_cited_article
2016.0    29
2019.0    26
2017.0    26
2020.0    24
2018.0    24
2013.0    22
2014.0    18
2010.0    17
2012.0    16
2015.0    14
2011.0    12
2009.0    12
2021.0    10
2007.0     9
2004.0     9
Name: journal, dtype: int64

In [60]:
# See mean of the most cited article citation 
df_mca_mean = df_group_mca.mean()
df_mca_mean = df_mca_mean.sort_values(by=['Citation_most_cited_article'],ascending=False)
Mean_info = df_mca_mean.Citation_most_cited_article
print(Mean_info.head(15))

Year_of_most_cited_article
1972.0    11300.000000
1967.0     7200.000000
1981.0     6700.000000
2000.0     4854.333333
2008.0     4319.333333
2012.0     2253.437500
1985.0     2000.000000
2018.0     1783.750000
2009.0     1727.666667
2015.0     1613.857143
1989.0     1450.000000
1966.0     1400.000000
1992.0     1257.000000
2010.0     1236.764706
2007.0     1228.222222
Name: Citation_most_cited_article, dtype: float64

In [63]:
# See mean of the impact factor
df_mca_mean_ipf = df_mca_mean.sort_values(by=['impact_factor'],ascending=False)
Mean_ipf_info = df_mca_mean_ipf.impact_factor
print(Mean_ipf_info.head(15))

Year_of_most_cited_article
2018.0    10.741667
1967.0     9.600000
2008.0     8.500000
2012.0     8.456250
1972.0     8.400000
1992.0     7.650000
1989.0     6.350000
1981.0     6.200000
1985.0     5.700000
2006.0     5.560000
2010.0     4.723529
1983.0     4.700000
2015.0     4.035714
2004.0     3.955556
2005.0     3.912500
Name: impact_factor, dtype: float64

In [65]:
# See mean of the article number
df_mca_mean_atn = df_mca_mean.sort_values(by=['article_number'],ascending=False)
Mean_atn_info = df_mca_mean_atn.article_number
print(Mean_atn_info.head(15))

Year_of_most_cited_article
1967.0    53900.000000
1981.0    43600.000000
1972.0    23800.000000
1983.0    11100.000000
1998.0     8300.000000
2008.0     7966.666667
1995.0     6042.000000
1977.0     5400.000000
2006.0     5331.600000
1989.0     5300.000000
2009.0     4969.833333
2007.0     4399.222222
2010.0     3975.764706
2005.0     3906.500000
2004.0     3691.222222
Name: article_number, dtype: float64